[project]
name = "cc-ampapi"
dynamic = ["version"]
authors = [
    { name = "k8thekat", email = "Cadwalladerkatelynn+AMPAPI@gmail.com" },
]
readme = { file = "README.md", content-type = "text/markdown" }
description = "A Python wrapper for the AMP API by CubeCoders"
requires-python = ">=3.10.0"
license = { file = "LICENSE" }
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Framework :: AsyncIO",
    "Topic :: Internet",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Utilities",
    "Typing :: Typed",
]
keywords = ["cubecoders", "cube coders", "amp", "api"]
dependencies = [
    "aiohttp>=3.7.4.post0",
    "dataclass-wizard>=0.22.2",
    "pyotp>=2.6.0",
]

[project.urls]
GitHub = "https://github.com/k8thekat/AMPAPI_Python"
Changelog = "https://github.com/k8thekat/AMPAPI_Python/blob/master/CHANGELOG.md"

[tool.ruff]
target-version = "py310"
line-length = 140
exclude = ["docs/extensions/*.py"]
select = ["ALL"]
ignore = [
    "ANN401",
    "D205", # Blank line, after first line in docstrings.
    "D301", # `r` backtick for code in docstrings.
    "D400", # First line end with a period in docstrings.
    "D401", # Ignore "Imperative Mood" statement for docstrings.
    "D415", # Ignore docstring punctuation.
    "ERA001", #Ignore commented out code.
    "FIX002", # Ignore TODO's telling you to "fix them".
    "F401",
    "F402",
    "F403",
    "F405",
    "PERF203",
    "PLR",
    "RUF001",
    "RUF002", # The character U+2013 "–" could be confused with the ASCII character U+002d "-", which is more common in source code.
    "RUF003", # The character U+2013 "–" could be confused with the ASCII character U+002d "-", which is more common in source code, this is for "COMMENTS"
    "RUF009",
    "RUF052", # for filtering "local dummy variable is accessed" eg. - vars using `_`
    "SIM105",
    "SLF001", # private function/attribute usage outside of the class it was defined.
    "TD002", # Ignore TODO's not having a link/url to an issue.
    "TD003", # Ignore TODO's not having a link/url to an issue.
    "TRY400", # Ingoring forced `logging.exception` statement's when using try/except.
    "T201", # Ignore print statements.
    "UP007",
    "UP034",
    "UP045", # Type var `Optional[X]` vs `X | None`
    "ANN401",
    "ASYNC240", # Because Umbra said "f anyio~"
    "C901", # Too complex functions.
    "D401", # Ignore "Imperative Mood" statement for docstrings.
    "ERA001", #Ignore commented out code.
    "FIX002", # Ignore TODO's telling you to "fix them".
    "FBT001", # Ignore "bool" type arguments and limited functionality statement.
    "FBT002", # Ignore "bool" type arguments and limited functionality statement.
]

[tool.ruff.lint.isort]
split-on-trailing-comma = false
combine-as-imports = true

[tool.ruff.lint.flake8-annotations]
allow-star-arg-any = true

[tool.ruff.lint.flake8-pytest-style]
fixture-parentheses = false
mark-parentheses = false
parametrize-names-type = "tuple"

[tool.pyright]
venvPath = "."
venv = ".venv"
typeCheckingMode = "strict"
pythonVersion = "3.10"
exclude = ["logs/**", "**/.venv/**", "**/.vscode-server/", "/usr/*", "**/node_modules", "**/__pycache__", "**/.*"]
include = ["ampapi"]
useLibraryCodeForTypes = true
reportIncompatibleMethodOverride = false

[tool.setuptools]
packages = ["ampapi"]
include-package-data = true

[tool.setuptools.dynamic]
version = { attr = "ampapi.__version__" }

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
